#!/usr/bin/env bash
set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run this installer with sudo." >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_PATH="/etc/kesher/raspberry-pis.json"
COMPANION_HOST=""
COMPANION_PORT="16622"
REST_PORT="9999"
SATELLITE_BUILD="${SATELLITE_BUILD:-stable}"
SATELLITE_BRANCH="${SATELLITE_BRANCH:-main}"
REINSTALL="false"

usage() {
  echo "Usage: sudo ./install-companion-satellite.sh [--host HOST] [--port PORT] [--rest-port PORT] [--config PATH] [--reinstall]"
  echo "  --host HOST      Companion server hostname or IP. Defaults to server_url host from raspberry-pis.json."
  echo "  --port PORT      Companion Satellite API port. Defaults to 16622."
  echo "  --rest-port PORT Satellite web configuration port. Defaults to 9999."
  echo "  --config PATH    Kesher Raspberry config. Defaults to /etc/kesher/raspberry-pis.json."
  echo "  --reinstall      Run the official Bitfocus installer even if satellite.service already exists."
}

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --host)
      if [[ "$#" -lt 2 ]]; then
        echo "--host requires a value." >&2
        exit 1
      fi
      COMPANION_HOST="${2:-}"
      shift
      ;;
    --port)
      if [[ "$#" -lt 2 ]]; then
        echo "--port requires a value." >&2
        exit 1
      fi
      COMPANION_PORT="${2:-}"
      shift
      ;;
    --rest-port)
      if [[ "$#" -lt 2 ]]; then
        echo "--rest-port requires a value." >&2
        exit 1
      fi
      REST_PORT="${2:-}"
      shift
      ;;
    --config)
      if [[ "$#" -lt 2 ]]; then
        echo "--config requires a value." >&2
        exit 1
      fi
      CONFIG_PATH="${2:-}"
      shift
      ;;
    --reinstall)
      REINSTALL="true"
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
  shift
done

extract_companion_host() {
  local config_path="$1"

  if [[ ! -f "${config_path}" ]]; then
    return 0
  fi

  python3 - "${config_path}" <<'PY'
import json
import sys
from urllib.parse import urlparse

try:
    with open(sys.argv[1], "r", encoding="utf-8") as handle:
        config = json.load(handle)
    parsed = urlparse(config.get("server_url", ""))
    print(parsed.hostname or "")
except Exception:
    print("")
PY
}

if [[ -z "${COMPANION_HOST}" ]]; then
  COMPANION_HOST="$(extract_companion_host "${CONFIG_PATH}")"
fi

if [[ -z "${COMPANION_HOST}" ]]; then
  echo "Could not determine Companion host. Pass --host <ip-or-hostname>." >&2
  exit 1
fi

if ! [[ "${COMPANION_PORT}" =~ ^[0-9]+$ ]] || ! [[ "${REST_PORT}" =~ ^[0-9]+$ ]]; then
  echo "Ports must be numeric." >&2
  exit 1
fi

OFFICIAL_INSTALL_URL="https://raw.githubusercontent.com/bitfocus/companion-satellite/main/pi-image/install.sh"

if [[ "${REINSTALL}" == "true" ]] || ! systemctl cat satellite.service >/dev/null 2>&1; then
  TMP_INSTALLER="$(mktemp)"
  trap 'rm -f "${TMP_INSTALLER}"' EXIT

  echo "Installing Companion Satellite from Bitfocus..."
  curl -fsSL "${OFFICIAL_INSTALL_URL}" -o "${TMP_INSTALLER}"
  SATELLITE_BUILD="${SATELLITE_BUILD}" SATELLITE_BRANCH="${SATELLITE_BRANCH}" bash "${TMP_INSTALLER}"
else
  echo "Companion Satellite is already installed. Use --reinstall to run the official installer again."
fi

install -d -m 0755 /boot
cat > /boot/satellite-config <<EOF
# Generated by Kesher Raspberry installer.
# Satellite imports this file on service start and then resets it to defaults.
COMPANION_IP=${COMPANION_HOST}
COMPANION_PORT=${COMPANION_PORT}
REST_PORT=${REST_PORT}
EOF
chmod 0666 /boot/satellite-config

systemctl daemon-reload
systemctl enable satellite.service
systemctl restart satellite.service

echo "Companion Satellite is installed and running."
echo "Target Companion server: ${COMPANION_HOST}:${COMPANION_PORT}"
echo "Satellite web UI: http://$(hostname -I | awk '{print $1}'):${REST_PORT}"
